/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/a16fQyTNOpV
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { IBM_Plex_Sans } from 'next/font/google'

ibm_plex_sans({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client"

import { useState } from "react"
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"

export function Minv3() {
  const [isDarkMode, setIsDarkMode] = useState(false)
  return (
    <div className={`flex flex-col min-h-[100dvh] ${isDarkMode ? "dark bg-gray-900" : "bg-white"}`}>
      <main className="flex-1 pt-32">
        <header className="fixed top-5 left-0 right-0 z-50 px-4 lg:px-6 h-16 flex items-center justify-center backdrop-blur-md bg-white/80 dark:bg-gray-900/80 shadow-lg rounded-t-2xl rounded-b-2xl w-[80%] mx-auto">
          <Link href="#" className="flex items-center justify-center" prefetch={false}>
            <MountainIcon className="h-6 w-6" />
            <span className="sr-only">Acme Web Development</span>
          </Link>
          <nav className="ml-auto flex gap-4 sm:gap-6 justify-center">
            <Link
              href="#"
              className="text-sm font-medium hover:underline underline-offset-4 dark:text-gray-400 dark:hover:text-gray-300"
              prefetch={false}
            >
              Services
            </Link>
            <Link
              href="#"
              className="text-sm font-medium hover:underline underline-offset-4 dark:text-gray-400 dark:hover:text-gray-300"
              prefetch={false}
            >
              Portfolio
            </Link>
            <Link
              href="#"
              className="text-sm font-medium hover:underline underline-offset-4 dark:text-gray-400 dark:hover:text-gray-300"
              prefetch={false}
            >
              About
            </Link>
            <Link
              href="#"
              className="text-sm font-medium hover:underline underline-offset-4 dark:text-gray-400 dark:hover:text-gray-300"
              prefetch={false}
            >
              Contact
            </Link>
          </nav>
          <Button variant="ghost" size="icon" className="ml-4" onClick={() => setIsDarkMode(!isDarkMode)}>
            {isDarkMode ? <SunIcon className="h-6 w-6" /> : <MoonIcon className="h-6 w-6" />}
            <span className="sr-only">Toggle dark mode</span>
          </Button>
        </header>
        <section className="w-full py-12 md:py-20 lg:py-28 xl:py-36 flex justify-center bg-white dark:bg-gray-900">
          <div className="container px-4 md:px-6 flex justify-center">
            <div className="grid gap-6 lg:grid-cols-[1fr_400px] lg:gap-12 xl:grid-cols-[1fr_600px] justify-center">
              <div className="flex flex-col justify-center space-y-4 items-center">
                <div className="space-y-2 text-center">
                  <h1 className="text-3xl font-bold tracking-tighter sm:text-5xl xl:text-6xl/none dark:text-gray-300">
                    Elevate Your Online Presence with Acme Web Development
                  </h1>
                  <p className="max-w-[600px] text-muted-foreground md:text-xl dark:text-gray-400">
                    Our team of experienced web developers specializes in creating custom, responsive websites that
                    drive results for your business.
                  </p>
                </div>
                <div className="flex flex-col gap-2 min-[400px]:flex-row justify-center">
                  <Link
                    href="#"
                    className="inline-flex h-10 items-center justify-center rounded-md bg-primary px-8 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50 dark:bg-gray-700 dark:text-gray-300 dark:hover:bg-gray-600"
                    prefetch={false}
                  >
                    Learn More
                  </Link>
                  <Link
                    href="#"
                    className="inline-flex h-10 items-center justify-center rounded-md border border-input bg-background px-8 text-sm font-medium shadow-sm transition-colors hover:bg-accent hover:text-accent-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50 dark:border-gray-600 dark:bg-gray-800 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-gray-300"
                    prefetch={false}
                  >
                    Contact Us
                  </Link>
                </div>
              </div>
              <img
                src="/placeholder.svg"
                width="550"
                height="550"
                alt="Hero"
                className="mx-auto aspect-video overflow-hidden rounded-2xl object-cover sm:w-full lg:order-last lg:aspect-square"
              />
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-20 lg:py-28 flex justify-center bg-white dark:bg-gray-900">
          <div className="container px-4 md:px-6 flex justify-center flex-col items-center">
            <div className="space-y-2 text-center">
              <div className="inline-block rounded-lg bg-muted px-3 py-1 text-sm dark:bg-gray-700 dark:text-gray-400">
                Our Portfolio
              </div>
              <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl dark:text-gray-300">
                Websites We've Built
              </h2>
              <p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                Take a look at some of the custom websites we've created for our clients. From e-commerce to corporate
                branding, we've got you covered.
              </p>
            </div>
            <div className="mx-auto grid max-w-5xl items-center gap-6 py-12 lg:grid-cols-2 lg:gap-12 justify-center">
              <img
                src="/placeholder.svg"
                width="550"
                height="310"
                alt="Portfolio Item"
                className="mx-auto aspect-video overflow-hidden rounded-2xl object-cover object-center sm:w-full"
              />
              <div className="flex flex-col justify-center space-y-4 items-center">
                <div className="grid gap-1 text-center">
                  <h3 className="text-xl font-bold dark:text-gray-300">Acme Clothing</h3>
                  <p className="text-muted-foreground dark:text-gray-400">
                    A modern e-commerce website for a leading fashion brand.
                  </p>
                </div>
                <div className="grid gap-1 text-center">
                  <h3 className="text-xl font-bold dark:text-gray-300">Apex Consulting</h3>
                  <p className="text-muted-foreground dark:text-gray-400">
                    A corporate website showcasing the company's services and expertise.
                  </p>
                </div>
                <div className="grid gap-1 text-center">
                  <h3 className="text-xl font-bold dark:text-gray-300">Zen Yoga Studio</h3>
                  <p className="text-muted-foreground dark:text-gray-400">
                    A responsive website for a local yoga studio, featuring class schedules and online booking.
                  </p>
                </div>
              </div>
            </div>
            <div className="flex justify-center">
              <Link
                href="#"
                className="inline-flex h-10 items-center justify-center rounded-md bg-primary px-8 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50 dark:bg-gray-700 dark:text-gray-300 dark:hover:bg-gray-600"
                prefetch={false}
              >
                View More
              </Link>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-20 lg:py-28 bg-muted dark:bg-gray-800 flex justify-center">
          <div className="container px-4 md:px-6 flex justify-center flex-col items-center">
            <div className="space-y-2 text-center">
              <div className="inline-block rounded-lg bg-muted px-3 py-1 text-sm dark:bg-gray-700 dark:text-gray-400">
                Get in Touch
              </div>
              <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl dark:text-gray-300">
                Let's Discuss Your Project
              </h2>
              <p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                Fill out the form below and one of our web development experts will be in touch to discuss your project
                requirements.
              </p>
            </div>
            <div className="mx-auto w-full max-w-sm space-y-2 flex justify-center">
              <form className="flex flex-col gap-4 w-full">
                <Input
                  type="text"
                  placeholder="Name"
                  className="max-w-lg flex-1 dark:bg-gray-700 dark:text-gray-300 dark:placeholder-gray-500"
                />
                <Input
                  type="email"
                  placeholder="Email"
                  className="max-w-lg flex-1 dark:bg-gray-700 dark:text-gray-300 dark:placeholder-gray-500"
                />
                <Textarea
                  placeholder="Message"
                  className="max-w-lg flex-1 dark:bg-gray-700 dark:text-gray-300 dark:placeholder-gray-500"
                />
                <Button
                  type="submit"
                  className="justify-center dark:bg-gray-700 dark:text-gray-300 dark:hover:bg-gray-600"
                >
                  Submit
                </Button>
              </form>
            </div>
          </div>
        </section>
      </main>
      <footer className="flex flex-col gap-2 sm:flex-row py-6 w-full shrink-0 items-center px-4 md:px-6 border-t justify-center dark:bg-gray-900 dark:border-gray-700">
        <p className="text-xs text-muted-foreground dark:text-gray-400">
          &copy; 2024 Acme Web Development. All rights reserved.
        </p>
        <nav className="sm:ml-auto flex gap-4 sm:gap-6 justify-center">
          <Link
            href="#"
            className="text-xs hover:underline underline-offset-4 dark:text-gray-400 dark:hover:text-gray-300"
            prefetch={false}
          >
            Terms of Service
          </Link>
          <Link
            href="#"
            className="text-xs hover:underline underline-offset-4 dark:text-gray-400 dark:hover:text-gray-300"
            prefetch={false}
          >
            Privacy
          </Link>
        </nav>
      </footer>
    </div>
  )
}

function MoonIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 3a6 6 0 0 0 9 9 9 9 0 1 1-9-9Z" />
    </svg>
  )
}


function MountainIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>
  )
}


function SunIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="4" />
      <path d="M12 2v2" />
      <path d="M12 20v2" />
      <path d="m4.93 4.93 1.41 1.41" />
      <path d="m17.66 17.66 1.41 1.41" />
      <path d="M2 12h2" />
      <path d="M20 12h2" />
      <path d="m6.34 17.66-1.41 1.41" />
      <path d="m19.07 4.93-1.41 1.41" />
    </svg>
  )
}
